[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colog = "1.3.0"
log = "0.4.26"
slo_rs = { version = "0.1.0", path = "../slo_rs" }
